### ISSUE TITLE
Get Transaction's list

### ISSUE THREAD

**Issue by Shumhard** [Mangopay/mangopay2-net-sdk#109]
Good day,

After updating mangopay sdk to 2.0.4 version I have issue with request of the transaction's list from Mangopay.

I tried to use next sdk methods with all overloads:

MangoPayApi api = new MangoPayApi();
/*---*/
api.Wallets.GetTransaction
api.Clients.GetTransactions
api.Clients.GetWalletTransactions
api.Users.GetTransactions
api.Users.GetTransactionsForBankAccount

Every times API returns error: {"Method not found: \"System.String[] System.String.Split(Char, System.StringSplitOptions)\"."}

Could you please advise how I can get a list of the transactions?

**Comment by mangomaxoasis** [comment]
Hi @Shumhard 
We've been looking into it
I'll keep you updated

**Comment by SoloJr** [comment]
Hi @Shumhard

Can you give us your part of code that is failing? From our existing tests, every method invoked by you works. Do you use any parameters, such as pagination or filtering?

**Comment by Shumhard** [comment]
Hi, @SoloJr 

Here part of the method:

MangoPayApi api = new MangoPayApi();
ConfigureMangoPayApi(api);
FilterTransactions mpFilter = new FilterTransactions();
mpFilter.Status = TransactionStatus.SUCCEEDED;
Sort mpSort = new Sort();
mpSort.AddField("CreationDate", SortDirection.desc);
Pagination pagination = new Pagination(1, 99);

/**/
try
{
     var mpTransactions4 = await new TaskFactory().StartNew(() => api.Wallets.GetTransactions(wallet.WalletId, pagination, mpFilter, mpSort));
}
catch (Exception ex)
{
    NLogHelper.Error(exc);
    throw;
}

wallet.WalletId is not null, and yes I use pagination, filtering and sorting.

**Comment by SoloJr** [comment]
Hi @Shumhard 

I have tried to replicate your error, but couldn't..

**Comment by SoloJr** [comment]
@Shumhard 

which .net framework version do you have. I'm pretty sure the error isn't in our sdk

I've tried to run multiple tests, but couldn't replicate your error.

**Comment by Shumhard** [comment]
v4.7.2

**Comment by mangomaxoasis** [comment]
Hi @Shumhard 
We've looked into it -> there are not obvious problems with the API or the SDK
Could you try making the API calls directly, bypassing the SDK, to understand if the API or the SDK is bugging 
https://docs.mangopay.com/endpoints/v2.01/transactions#e222_the-transaction-object
Max

**Comment by xps** [comment]
Hi @mangomaxoasis 

We have the same problem, running on .NET 4.6.1

The problem is that the `GetTransactions` method calls `System.String.Split(Char, System.StringSplitOptions)`, but this overload [does not exist on .NET Framework 4.x][2].

It seems to [only exist in .NET Standard 2.1][0] ([and not 2.0][3]), but .NET Framework 4.x [only implements up to .NET Standard 2.0][1]

[0]: https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.1
[1]: https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/
[2]: https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netframework-4.8
[3]: https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.0

**Comment by xps** [comment]
PS: according to the call stack the missing method is called from `MangoPay.SDK.Core.RestTool.ReadResponseHeaders`, although for some reason I only see a call to `Split(char)` in the source code. Maybe it was updated recently?

```
[MissingMethodException: Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.]
   MangoPay.SDK.Core.RestTool.ReadResponseHeaders(IRestResponse restResponse, ListPaginated`1 listPaginated) +0
   MangoPay.SDK.Core.RestTool.DoRequestList(String urlMethod, Pagination pagination, Dictionary`2 additionalUrlParams) +1621
   MangoPay.SDK.Core.RestTool.RequestList(ApiEndPoint endPoint, Dictionary`2 requestData, Pagination pagination, Dictionary`2 additionalUrlParams) +99
   MangoPay.SDK.Core.RestTool.RequestList(ApiEndPoint endPoint, Dictionary`2 requestData, Pagination pagination) +61
   MangoPay.SDK.Core.APIs.ApiBase.GetList(MethodKey methodKey, Pagination pagination, Sort sort, Dictionary`2 additionalUrlParams, String[] entitiesId) +230
```

**Comment by xps** [comment]
Sorry for the spam.
After further testing, I have found that, at least in our case, the following versions work or do no work:

 - 2.0.0 ok
 - 2.0.2 ok
 - 2.0.3 not ok
 - 2.0.4 not ok
 - 2.1.0 not ok

**Comment by mangomaxoasis** [comment]
Hi @xps  @Shumhard error treated in latest release

**Comment by mangomaxoasis** [comment]
Hi @xps 
Would it be possible for us to speak about this issue? Could you contact me maxime.gavanon@mangopay.com
Regards,
Max
