### ISSUE TITLE
No Value for TotalItems and TotalPages

### ISSUE THREAD

**Issue by Nito-17** [Mangopay/mangopay2-net-sdk#115]
Hi,

I tried  *.Users.GetTransactions() and *.Wallets.GetTransactions() with all overloads and the async versions but always get the same result, which is TotalItems & TotalPages = 0

![MangoPayListPaginatedResult](https://user-images.githubusercontent.com/70749939/92223265-844c6a80-eea0-11ea-893f-17a4fad37035.png)

**Comment by mangomaxoasis** [comment]
Hi @Nito-17 
Our tech team's looking into it 
Max

**Comment by mangomaxoasis** [comment]
released
