### ISSUE TITLE
GetTransactions() will return an exception

### ISSUE THREAD

**Issue by sameerasmr** [Mangopay/mangopay2-net-sdk#116]
We are using MangoPay 2.1.1 with .Net Framework 4.7.2 and it getting the error as "**Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.**"

![123](https://user-images.githubusercontent.com/71332293/93218940-6d532580-f788-11ea-8ff6-be54ff7fd49c.JPG)

And

I got the error as  **The requested resource does not support http method 'GET'.**  for the below code.

![image](https://user-images.githubusercontent.com/71332293/93876996-5b780200-fcf5-11ea-9b2c-24fdc0989c8e.png)

I have required to solve the above without downgrade the current .Net version (4.7.2). Could you please advice me.

Thanks in advance

**Comment by mangomaxoasis** [comment]
Hi @sameerasmr 
Our tech team's looking into this issue 
max

**Comment by SoloJr** [comment]
Hi @sameerasmr 

We couldn't reproduce your error. I have updated the MangoPaySdk to use .Net Framework 4.7.2 as well. See [this branch](https://github.com/Mangopay/mangopay2-net-sdk/tree/bugfix/issue_116) for details, more exactly [this](https://github.com/Mangopay/mangopay2-net-sdk/commit/36dcc9a50c169d79cfad827ee261071b1dbc9159).

**Comment by mangomaxoasis** [comment]
Hi @sameerasmr 
We've had a similar issue here https://github.com/Mangopay/mangopay2-net-sdk/issues/109
The issue is more with the .NET Standard not the framework verison
What Standard are you using?

**Comment by sameerasmr** [comment]
Hi @mangomaxoasis ,

We are using .NET framework 4.7.2 that uses .NET 2.0 standard.
You can see the test project via the below link [](url)

It is great, if you can specified which needs to be modified/added.

Sameera


> Hi @sameerasmr
> 
> We couldn't reproduce your error. I have updated the MangoPaySdk to use .Net Framework 4.7.2 as well. See [this branch](https://github.com/Mangopay/mangopay2-net-sdk/tree/bugfix/issue_116) for details, more exactly [this](https://github.com/Mangopay/mangopay2-net-sdk/commit/36dcc9a50c169d79cfad827ee261071b1dbc9159).

Hi @SoloJr , 

Yes. I saw that you have configured .Net 4.7.2, but still I'm getting the error on .Net 4.7.2

Sameera

**Comment by sameerasmr** [comment]
Hi @mangomaxoasis ,

We are using .NET framework 4.7.2 that uses .NET 2.0 standard.

I have created a test project just test to the above issue and you can download it via the below link.
[https://we.tl/t-ONjS93eAXP](url)

it is great, if you can specify which needs to be modified/added to resolve the issue.

Thanks in advance

Sameera

**Comment by mangomaxoasis** [comment]
Hi @sameerasmr
 
Are you sure the method is not a 2.1 Standard method? 
This is a recurring issue  
As per #109 

Max

**Comment by sameerasmr** [comment]
Hi @mangomaxoasis ,

Yes. We are using .Net 4.7.2 version.

![image](https://user-images.githubusercontent.com/71332293/94381486-3224ff00-0157-11eb-8c33-89f026210dce.png)

You can see it with the sample project what I have uploaded and share the link in the same thread.

Thanks

Sameera

**Comment by sameerasmr** [comment]
Hi @SoloJr ,

It was not success with the .NET 4.7.2 with Mango Pay 2.1.3, but it works with MangoPay 2.0.0.

Thank you

Sameera.

**Comment by mangomaxoasis** [comment]
Hi @sameerasmr 
Indeed the issue is on the interaction of the the dotnet framework and the dotnet standard, in 2.1 several methods are deprecated 
Can you confirm which version of the **Standard** you are using

**Comment by sameerasmr** [comment]
Hi @mangomaxoasis ,

We are using .NET standard 2.0.

You can see the test projects what we recently build with the MangoPay 2.1.3 on below url,

https://github.com/aldari/mongopay-issue

We are getting the same error for the above test projects (.NET 4.7.2 and MangoPay 2.1.3) as "**Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.**"

We have downgraded MangoPay version to 2.0.0 with the same .NET version works well, but some of features will not be available on the MangoPay 2.0.0, then we cannot go with that version.

Due to the later implementation, we are not able to downgrade the .NET version as well as the MangoPay version.

As I noticed, one of comment on the below issue is align with me.

https://github.com/Mangopay/mangopay2-net-sdk/issues/109

![image](https://user-images.githubusercontent.com/71332293/94548363-3db71980-026e-11eb-9864-4e92ab594438.png)

Thanks in advance.

Regards,
Sameera

**Comment by mangomaxoasis** [comment]
Hi @sameerasmr ,

We've released a patch -> it's release https://github.com/Mangopay/mangopay2-net-sdk/releases/tag/2.1.6

(Please use the latest release, we had to release in several parts as there were impacts on our auto-deploy and QA processes )

We've removed the problematic functions such that things work across the different framework versions

**Comment by sameerasmr** [comment]
Hi @mangomaxoasis ,

I could installed the latest MangoPay version (2.1.6) and it works properly with .NET 4.7.2 without getting errors.
Thank you very much for the quick respond and the commitment.

Thank you

Regards,
Sameera
