### ISSUE TITLE
[Question] Can/Should the .NET sdk be used in Unity3d mobile apps?

### ISSUE THREAD

**Issue by rubenhorn** [Mangopay/mangopay2-net-sdk#128]
Can I use this sdk in the C# code of a Unity3d iOS/Android app?

Is there any reason why you should not to do this?

**Comment by mangomaxoasis** [comment]
Hi @rubenhorn 
Investigation ongoing

**Comment by mangomaxoasis** [comment]
Hi @rubenhorn 
Unfortunately no, this isn't possible
max
