### ISSUE TITLE
GetBankAccountsAsync hides data specific to bank account type

### ISSUE THREAD

**Issue by M0ns1gn0r** [Mangopay/mangopay2-net-sdk#137]
`api.Users.GetBankAccountsAsync` returns a collection of `BankAccountDTO`s, and that would be OK if the actual instances would be of the most concrete type (`BankAccountIbanDTO`, `BankAccountOtherDTO`, etc.). That is not the case, though.

After retrieving the list of bank accounts, I **have no access** to *IBAN, AccountNumber, BIC*, etc... Getting this data would require making N additional requests to `api.Users.GetBankAccountIbanAsync` for each of N results (and then probably experience throttling because of the rate limiting).

P.S. the actual [REST API](https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e28_list-bank-accounts-for-a-user) does return the full info for each bank account.

**Comment by mangomaxoasis** [comment]
Hi @M0ns1gn0r 
We're looking into it

**Comment by M0ns1gn0r** [comment]
Seems to be already fixed.
