### ISSUE TITLE
Possibility to upgrade this SDK to .NETStrandard/.NETCore/.NET 5 ?

### ISSUE THREAD

**Issue by stringformat** [Mangopay/mangopay2-net-sdk#142]
I would like to know if an SDK upgrade is planned to .NETCore/.NETStandard or .NET 5? Thanks

**Comment by M0ns1gn0r** [comment]
It already supports `netstandard2.0`, so should work fine with .NET5.

**Comment by Samkhan87** [comment]
Yes

**Comment by SoloJr** [comment]
@fredericdelordm please close this, as the SDK supports .NET5
