### ISSUE TITLE
RestSharp incompatability with new version

### ISSUE THREAD

**Issue by mawendel** [Mangopay/mangopay2-net-sdk#156]
I am using RestSharp in my own project. After updating to the new 107 version, MangoPay API calls now give me the following error:

```
An error occurred while writing to logger(s). (Could not load type 'RestSharp.IRestResponse`1' from assembly 'RestSharp, Version=107.3.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.) (Could not load type 'RestSharp.IRestResponse`1' from assembly 'RestSharp, Version=107.3.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.) (Could not load type 'RestSharp.IRestResponse`1' from assembly 'RestSharp, Version=107.3.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.)
```
There are breaking changes where most of the interfaces have been removed. The code change itself is really small.
Please update your RestSharp to the newest version!

**Comment by fredericdelordm** [comment]
Hello @mawendel,

We are looking into it

**Comment by SoloJr** [comment]
[fixed here, will be released pretty soon](https://github.com/Mangopay/mangopay2-net-sdk/pull/159)
