### ISSUE TITLE
Solution for projects on the .NET Framework?

### ISSUE THREAD

**Issue by xps** [Mangopay/mangopay2-net-sdk#171]
Hello,

The latest version of the SDK targets .NET Standard 2.1, which is implemented by .NET Core and .NET, but not by .NET Framework.
The .NET Framework only supports up to .NET Standard 2.0.

We maintain several ASP.NET MVC applications that run on .NET Framework 4.7 and make use of the MangoPay SDK.
Recently, a new parameter has been introduced on the 'create user' API (I am referring to 'UserCategory').
We need to update our SDK to pass this new mandatory parameter.
However, the highest SDK version that we can update to is 2.11, and this version does not support the passing of the 'UserCategory' parameter.

We are stuck as we cannot update to the latest SDK and rewriting several major applications to run on ASP.NET Core is not an option.

What solution can we have for legacy applications running on the .NET Framework?
Can the requirements of the SDK be lowered so that it targets .NET Standard 2.0 instead of 2.1?

Thanks

**Comment by fredericdelordm** [comment]
Hello @xps,

We are looking into it.

**Comment by xps** [comment]
Hello @fredericdelordm,

I have also been looking into it. There are not many changes required to make the SDK compatible with .NET Framework (4.x).

I am about to submit a pull request. Here's a summary of the changes:

- The SDK compilation now targets .NET Standard 2.0 instead of .NET Standard 2.1 (and will keep targeting .NET 6 as well).
- The code compiles fine on .NET Standard 2.0 without changes.
- However, there is a difference in runtime behavior between the 2 frameworks. In particular, RestSharp uses a different HTTP client under the hood for .NET 6 and .NET 4.x. On .NET 4.x, the HTTP client throws an exception when a 'Content-Type' HTTP header is passed to GET requests. I made 2 changes to fix this problem: 1) I made sure that this protocol exception is properly thrown when it happens (before, it would trigger a NullReferenceException). 2) I excluded the 'Content-Type' header from GET requests (from the HTTP specifications, this header only applies to requests that have a body).
- I made sure the unit tests run on both .NET 6 and .NET 4.8 to make sure that both underlying HTTP implementations are tested.

**Comment by fredericdelordm** [comment]
Nice, 

When do you plan to submit the PR? The team will review it asap.

**Comment by xps** [comment]
Here it is: https://github.com/Mangopay/mangopay2-net-sdk/pull/174

**Comment by xps** [comment]
Hello @fredericdelordm 
Was the team able to look at the PR?
I am available should they need any clarifications.
Thanks
