### ISSUE TITLE
Common.Logging with VNext RC2 and net451

### ISSUE THREAD

**Issue by pierregaboriaud** [Mangopay/mangopay2-net-sdk#19]
Hello !

I try to use the mangopay NuGet package (1.0.89) in my project which use the latest .net framework (NetCore 1.0 / VNext RC2 / ASP.NET 5 MVC 6) that also support .net 4.5.1

I'm having some problems with the Common.Logging library you use.

# Example
```
_api = new MangoPayApi();
_api.Config.ClientId = _clientId;
_api.Config.ClientPassword = _clientPass;

_api.Users.GetAll();
```

### Error
> Method not found: 'Boolean System.Reflection.MethodBase.op_Equality(System.Reflection.MethodBase, System.Reflection.MethodBase)'.

### StackTrace
>  at Common.Logging.LogManager.GetCurrentClassLogger()
>    at MangoPay.SDK.Core.RestTool..ctor(MangoPayApi root, Boolean authRequired)
>    at MangoPay.SDK.Core.APIs.ApiBase.GetList[T](MethodKey methodKey, Pagination pagination, String entityId, String secondEntityId, Sort sort, Dictionary`2 additionalUrlParams)
>    at MangoPay.SDK.Core.APIs.ApiUsers.GetAll()
>    [...]

# Example 2
```
_api = new MangoPayApi();
 _api.Config.ClientId = _clientId;
_api.Config.ClientPassword = _clientPass;
 _api.Config.LoggerFactoryAdapter = new Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter();
_api.Users.GetAll();
```

### Error
> Could not load file or assembly 'System, **Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

### StackTrace
> at Common.Logging.Configuration.ArgUtils.TryParseEnum[T](T defaultValue, String stringValue)
>    at Common.Logging.Simple.AbstractSimpleLoggerFactoryAdapter..ctor(NameValueCollection properties) in c:\_oss\common-logging\src\Common.Logging.Portable\Logging\Simple\AbstractSimpleLoggerFactoryAdapter.cs:line 153
>    [...]

# Solution ?
LogManager.GetCurrentClassLogger() seems to be obsolete

**Comment by pierregaboriaud** [comment]
Can you update the nuget package ?

**Comment by hobailey** [comment]
@pierregaboriaud done :-)
