### ISSUE TITLE
ExecutionDate can never be null

### ISSUE THREAD

**Issue by gareththackeray** [Mangopay/mangopay2-net-sdk#21]
I just updated the SDK to the latest version.  I am getting errors in my application code because PayIns that have not been exectuted are getting their ExecutionDate set to default(DateTime) instead of null.

This is because of this commit https://github.com/Mangopay/mangopay2-net-sdk/commit/b3641e79d38ea406d1f20e3ca33dc05986c5632a.  

If for some reason you need to have different behaviour for different nullable DateTimes I would suggest you should have separate converters are be able to pass in a parameter on the constructor.

**Comment by hobailey** [comment]
@gareththackeray this is now resolved :-) Thanks for flagging it up, and sorry for the delay getting back to you;
