### ISSUE TITLE
Newest verion on Nuget

### ISSUE THREAD

**Issue by sebvst** [Mangopay/mangopay2-net-sdk#25]
Hello,

thank you for the good SDK. I have one more request:

Could you put the latest version to Nuget. Right now I can only get the version from July through Nuget.

Thank you in advance!

Sebastian

**Comment by hobailey** [comment]
Hey, thanks for your feedback. We're working on getting the latest version live (we've made some changes since the last deploy which we just need to finish up), and I'll let you know when we have :-)

**Comment by sebvst** [comment]
Thank you for the answer. I will wait then. paypal looks good :)

**Comment by hobailey** [comment]
Hmm, don't get too excited about PayPal - I'm afraid is still in private beta, and won't be publicly available for a while :-/

**Comment by hobailey** [comment]
Sorry again for the huge delay @sebvst, but I'm happy to report that the blockage has been resolved and Nuget has now been updated :-)
