### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by Ponant** [Mangopay/mangopay2-net-sdk#26]
Hi,
Is it possible to have .Net Core support for ASP.NET Core?

**Comment by mickaelpois** [comment]
Hello @Ponant !
We're looking at this right now, we hope we will provide you this support ASAP.

Thanks !

**Comment by Ponant** [comment]
@mickaelpois , that is great, finally! Move directly to .Net Core 1.1 and prepared for 1.2 coming up during spring 2017 or so. Also check out if it needs a singleton, transient or scoped service in Startup. Cheers

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add .NET core support](https://trello.com/c/Bga2tL5u/144-add-net-core-support)

**Comment by NicolasPerego** [comment]
Hi, I will code a .NET Core web application in october, using MangoPay, do you think you'll have the .Net Core API ready for this timeline ? Thank you

**Comment by NicolasPerego** [comment]
Well... You deleted the your post concerning a planning of this evolution since I posted mine. Does it means it's not scheduled anymore ? Please at least answer me, I need to know wich payment provider I have to choose. Thanx

**Comment by mickaelpois** [comment]
Good afternoon @NicolasPerego,

I can't remember if there was a previous comment about .NET Core support, and if it was deleted.
Please be sure that if it was, it was not intentional. Sorry for any confuson about this.

This project was on hold, but have been recently relaunched! We hope that we could give a .NET Core support in the next couple of months.

We will provide you every updates about this project on this feed.

Have a nice day,

Mickaël

**Comment by NicolasPerego** [comment]
Great news ! Thanx a lot

**Comment by hobailey** [comment]
Hey, quick update on this: we've taken the time to look into the what would be required, and contary to what we originally thought, the changes required are quite significant, and non-compatible with the existing SDK, which would mean running two different .NET SDKs in parellel which is not something we're currently keen to do at this time I'm afraid.
Our .NET developer team are currently very focused on the v2 of the Dashboard which we're excited to release in a few months, so perhaps we'll be able to put the Core support back on the table at that stage.

**Comment by NicolasPerego** [comment]
Hi hobailey. I must say I'm disappointed by the news. .NET Core is released for more than a year now, and I'm suprised you're only discovering now it's not compatible with your actual SDK. Your .NET dev team should maybe do more technological watch if they dont want to be outdated by the tech they master. Anyway, you should know that most of new .NET web app will use .NET Core, and you're probably will missing some buisness here, as your competitors have already released .NET Core SDKs (for months). Sorry for the rant, I was really hopping to use MangoPay, and I'm really disappointed.

**Comment by NicolasPerego** [comment]
Hi hobailey, I had a second look at your API today, and with the recent release of .neststandard 2.0, and some new releases of your dependencies, it took me about 30mn to make your API to .NET Core compliant.

No optimization, no usage of async, only creating a new library project netstandard, and adding the right dependencies. Only 2 tests are not ok, but if I understand correctly the errors, they're a not technical problems.

Sorry for not sharing it here, but I'm not familiar with git and I don't have any time to learn it now. Contact me if you want the project, i'll send you a link to download it.

**Comment by NicolasPerego** [comment]
I managed to make a full asynchronous API for ASP.NET Core 2.0 from this base (not a fork, a new project). You can find it there : https://github.com/NicolasPerego/mangopay-net.core-sdk.

I hope it will help you, or other users.

**Comment by mickaelpois** [comment]
Hi @NicolasPerego,

A big thanks to you for your work, as it seems to be very valuable !
We have to know now what is the best way for all of us to make it easy to maintain with all of our new functionalities to come.

Mickaël

**Comment by NicolasPerego** [comment]
Thank you for having a look at my work @mickaelpois.

I don't see any easy way to maintain it, but to adapt each new fonctionnality to the new .NET Core project... :/

I'm still struggling with the logging system, which wasn't appearing as a problem in the tests. I can't find a way to make the "Common.Logging.Log4Net208" package works as logger with "Common.Logging" or "Common.Logging.Core" packages. Since you probably have a better understanding of this Logging system than me, if you guys have some time to have a look at this, please do, I have to move on to other devs on my project for now.

**Comment by NicolasPerego** [comment]
OK, I found the problem with Common.Logging/log4net, it has nothing to do with the MangoPay SDK.

It comes from log4net, they did not made adjustment since the netstandard 2.0 is out (see my last comment in https://github.com/apache/logging-log4net/pull/14).

I mage a log4net.dll with a slight adjustment, and it works perfectly with Common.Logging and the SDK.

Let's hope log4net will correct this.

**Comment by Guymestef** [comment]
Any news about .net core support?

**Comment by vannicktrinquier** [comment]
Any plan to support it soon ?

**Comment by Herostwist** [comment]
Hi. This SDK is now the only dependancy we are waiting for to support netstandard2.0
Any update on planned support?

**Comment by poke** [comment]
Is there an update on this? In 2019 this is a very huge blocker considering that .NET is strongly moving to .NET Core now.

If this is *just* waiting for code review for over a year now, maybe you should just develop this in the open (i.e. open a pull request) and have the community help with the review.

**Comment by NicolasPerego** [comment]
@poke If you're in a hurry and can't wait for an official release, I'm using in production for about 1 year the Core 2.0 compliant (fully async) code I adapted from here, without any trouble. I try to update it when there's a new release.

Only glitch was about log4net compatibility, and I modified their code to make it work long time ago, but I guess you can use other loggers (not tried), or tell me if you need the dll.

**Comment by poke** [comment]
@NicolasPerego Thanks for the offer! Right now, I am evaluating Mangopay and its API, so having access to an officially supported SDK library is somewhat important. Depending on our requirements, I maybe would rather use the APIs in a direct way than having to rely on a third-party library for payment-related things. I will keep your library in mind though, so thanks again for the offer!

That being said: Official .NET Core support being in the works for over 2 years is not the best sign.

**Comment by NicolasPerego** [comment]
Honestly, the Mangopay API is very well done and easy to use, the only problem for me was the big delay to deliver .NET Core release.

**Comment by Herostwist** [comment]
@mickaelpois This issue has been open for nearly three years. We have had to make the unfortunate decision to change payment provider purely for the reason Mangopay doesn't seem to show any interest in official support for netstandard any time soon. It's a shame, but people can't wait forever and three years is nearly forever for the .Net ecosystem.

**Comment by reghrafa** [comment]
I think this issue could be easily fixed by moving to .Net Standard 1.1 since Net 4.5 and Net Core 1.0 would be supported! That also would mean just one code base and a future proof SDK! I have created Issue #67 targeting this proposal.

**Comment by codingcronus** [comment]
Any updates on this? My company is also looking for an escrow payment provider, but the fact that you have spent 3 years without providing an official .net core/standard solution is very concerning. From a business perspective we think: If this is such a complex task for you, how would you cope with other urgent business requirements?
I would really like to go with MangoPay, but I need some official response soon, thanks.

**Comment by JuanGarciaCarmona** [comment]
Today I published this: https://github.com/JuanGarciaCarmona/mangopay-net-core-sdk

**Comment by SoloJr** [comment]
This is actually done by the MangoPaySDK as well.
