### ISSUE TITLE
Add the HttpStatusCode in 'ResponseException' object

### ISSUE THREAD

**Issue by jcoqueret** [Mangopay/mangopay2-net-sdk#29]
Hello,

In order to manage exceptions raised from the SDK, it will be appriciated to add the **HttpStatusCode** in the exception object named '**ResponseException**'. This way, it will be possible to differenciate network issues for example and implement a retry policy.
For now, we can check if the ResponseError property is null or not but it is not the solution at all.

What do you think about that ?

**Comment by hobailey** [comment]
Hey @jcoqueret, thanks for the feedback - we've just added this with https://github.com/Mangopay/mangopay2-net-sdk/commit/fc9a8f2235aee1b84914d560b4badbe7f3d54a0e :-)
