### ISSUE TITLE
Could not load type 'Common.Logging.LogManager'

### ISSUE THREAD

**Issue by xps** [MangoPay/mangopay2-net-sdk#3]
Hi,

I'm having the following error when trying to use the SDK:

> Could not load type 'Common.Logging.LogManager' from assembly 'Common.Logging.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e'.

Steps to reproduce:
 - Create a brand new C# console application
 - Add the SDK using the package manager: `Install-Package mangopay2-sdk`
 - Make an API call

For example:

    var mangoPayClient = new MangoPayApi();

    mangoPayClient.Config.ClientId = "***";
    mangoPayClient.Config.ClientPassword = "*********";
    mangoPayClient.Config.BaseUrl = "https://api.sandbox.mangopay.com";

    var user = mangoPayClient.Users.Get("123456");

Not sure what is going on, but since it happens in an empty app without other references I would assume it is the NuGet package that's broken?

Help would be much appreciated.

Thanks
Xavier

**Comment by hobailey** [comment]
Hi @xps, thanks for this feedback. Although we are able to reproduce the same problem, our initial research has been unable to identify the problem. We're looking into this further and I will update you via this thread when I have more info :-)

**Comment by etiennepierrot** [comment]
The nuget package has been updated. Update your package, it should work, now.
