### ISSUE TITLE
API v2.01 - Error creating a new natural user 

### ISSUE THREAD

**Issue by diogorodriguessr** [Mangopay/mangopay2-net-sdk#35]
Hello,

We're using your SDK for .Net and we have no control of the properties the userNaturalPostDto contains or doesn't contain. When the post to create a new natural user is made, it has the Capacity property already filled because it's of type Enum and enums have default values in .Net (in this case, NotSpecified=0). The enum should contain the value Normal rather than Default.

I already chatted with Tikhoze about this, she said that this issue was already raised in your team to be fixed. She suggested to create an issue here on GitHub to accelerate the process.

Regards,
Diogo Rodrigues - SyndicateRoom

**Comment by hobailey** [comment]
Hey Diogo, thanks for the feedback and sorry again for this error. I've just fixed this with https://github.com/Mangopay/mangopay2-net-sdk/commit/da2a5f88167234066f927cfa31f84a438b07680a and a new version with this patch will be on Nuget shortly.

**Comment by diogorodriguessr** [comment]
Hi @hobailey, could you please send the sdk dll updated with that fix?

**Comment by hobailey** [comment]
Do you mean deploy it to Nuget?

**Comment by diogorodriguessr** [comment]
Yes @hobailey

**Comment by hobailey** [comment]
OK, we have some technical problems with the deploy, but we'll hopefully get it sorted next week - I'll keep you up to date here.

**Comment by diogorodriguessr** [comment]
Can you send me a ZIP file with the updated SDK? This is urgent because we need to deploy a new version with this change.

**Comment by hobailey** [comment]
I suggest you download the zip directly from Github :-)

**Comment by diogorodriguessr** [comment]
Sorry but this didn't fix the issue. I can see that the value Not Specified was changed to NORMAL, but in the request if I ignore the capacity type it will still use the default value that is Not Specified which will trigger the same error.

**Comment by hobailey** [comment]
There were two problems (incorrect enum value, and the wrong default value) - I thought from your first message you were only stuck with the first one which was indeed corrected in that version. The second problem will be fixed in a new release which will be done tomorrow - I'm very sorry for the confusion with that.

**Comment by hobailey** [comment]
Just to let you know, the new version is now available on Nuget (v1.1.0)
