### ISSUE TITLE
Stop making breaking changes as minor version increments 

### ISSUE THREAD

**Issue by Herostwist** [Mangopay/mangopay2-net-sdk#38]
Recently updated nuget to version 1.0.94 from 1.0.92. 
Such a minor version increment should not contain breaking changes.

Wallet DTO amounts changed from int to long causing compile time errors.

More worrying is that UserNaturalPostDTO now has a default **CapacityType.NotSpecified** field that breaks all requests that now return the error {"Capacity":"NotSpecified is not a valid Capacity"}

The constructor for UserNaturalPostDTO doesn't even contain CapacityType, so there is not even a compiler error.

Very bad form.

**Comment by Herostwist** [comment]
I also cant find any documentation on capacity 
https://docs.mangopay.com/endpoints/v2/users#e255_create-a-natural-user
What does CapacityType.NORMAL even mean?

**Comment by hobailey** [comment]
Hi @Herostwist, I'm really sorry for the inconvience and time lost - I totally agree that 
a) we should have had a major version for this update (we haven't been able to deploy to Nuget for a year, hence there being so many changes, some even breaking)
b) the docs should explain what the field `Capacity` means (I've just updated this - it was an oversight on our side) but more importantly that the current implementation for this new parameter has been done incorrectly, hence why you're having problems. A couple of required fixes have been done and a new version will be pushed to Nuget in the next few days.

**Comment by Herostwist** [comment]
Thanks @hobailey 
According to the new docs (https://docs.mangopay.com/endpoints/v2/users#e255_create-a-natural-user), capacity is optional, but I can find no way of not specifying it using the SDK. Will this be fixed in the next version?

**Comment by hobailey** [comment]
It is indeed optional, and the new version will resolve that - until it's on Nuget, you can grab it from the repo here if you want.

**Comment by Herostwist** [comment]
groovy. thanks.

**Comment by hobailey** [comment]
Just to let you know, the new version is now available on Nuget (v1.1.0)
