### ISSUE TITLE
Support for asynchronous programming model

### ISSUE THREAD

**Issue by manuel-guilbault** [Mangopay/mangopay2-net-sdk#40]
The asynchronous programming model (`async`/`await` + `System.Threading.Tasks.Task`) has been around for a while now. It would be great if the MangoPay .NET API supported this model.

**Comment by NicolasPerego** [comment]
I managed to make a **full asynchronous** API for ASP.NET Core 2.0 from this base (not a fork, a new project). You can find it there : https://github.com/NicolasPerego/mangopay-net.core-sdk.

I hope it will help you, or other users.
