### ISSUE TITLE
Support for Address Verification System

### ISSUE THREAD

**Issue by Herostwist** [Mangopay/mangopay2-net-sdk#46]
Would be nice if the SDK supported the new Address Verification System.

[https://docs.mangopay.com/guide/avs](https://docs.mangopay.com/guide/avs)

**Comment by mickaelpois** [comment]
Hello @Herostwist !

Thanks for your interest in this new feature :)
We will deploy AVS support in the coming weeks, and we will let you aware of any update here.

Mickaël
