### ISSUE TITLE
User.Wallets.Transactions.Get server returns Error 500 when using DESC sorting

### ISSUE THREAD

**Issue by emg-85** [Mangopay/mangopay2-net-sdk#47]
Good day. I'm using mangopay .Net api:

/*--------------------------------------*/
Sort mpSort = new Sort();
                    mpSort.AddField("CreationDate", SortDirection.desc);

api.Wallets.GetTransactions(
                        walletId,
                        new Pagination(1, 25), 
                        new FilterTransactions(), 
                        mpSort)
/*--------------------------------------*/

When calling this method with pagination AND sorting DESC server returns 500 error, if total items on the last page is LESS than specified in pagination.
Example:
Overall items: 5
Method call params: new Pagination(2,4) (second page, 4 items per page)
Result: server error 500.

Fiddler:

**Request**:
GET https://api.sandbox.mangopay.com/v2.01/********/wallets/50866025/transactions?page=2&per_page=10&Sort=CreationDate%3Adesc HTTP/1.1
Content-Type: application/json
Authorization: bearer fd96f31a348549bfb64b1a5c0a42e499
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, application/json
User-Agent: RestSharp/104.5.0.0
Host: api.sandbox.mangopay.com
Accept-Encoding: gzip, deflate

**Response**:
HTTP/1.1 500 Internal Server Error
Date: Sun, 24 Jun 2018 06:18:23 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 139
Connection: keep-alive
Set-Cookie: __cfduid=d04cb00e6c6bef5f5411f2229a5cbb3b01529821073; expires=Mon, 24-Jun-19 06:17:53 GMT; path=/; domain=.mangopay.com; HttpOnly
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 42fd12eb4e718f81-DME

{"Message":"Internal Server Error","Type":"other","Id":"e948737e-9c26-435d-ad15-c0b8a66c1d5b#1529821073","Date":1529821104.0,"errors":null}

Any help would be appriciated. Thank you.

**Comment by SoloJr** [comment]
cannot reproduce
