### ISSUE TITLE
Download/Get infos "Transaction Receipt" with API

### ISSUE THREAD

**Issue by NicolasPerego** [Mangopay/mangopay2-net-sdk#48]
In the Dashboard (v1), there's a possibility for each "Pay-in" transaction to download the "Transaction Receipt" which contains useful informations.

Would it be possible to download it through the API, or at least get the informations through the API ?

Thanx

**Comment by SoloJr** [comment]
@mickaelpois could you please tell me if this issue is still valid and should it be taken into consideration?

**Comment by mickaelpois** [comment]
@SoloJr I'm closing it, not really related to our .NET SDK :)

**Comment by mpaucot** [comment]
I'm also looking to download receipt programmatically and the api mention nothing about it.
