### ISSUE TITLE
Error adding User Card details

### ISSUE THREAD

**Issue by CarlosKoffi** [Mangopay/mangopay2-net-sdk#49]
Hi , I got an error adding a User card with mango api using sdk

RestClient client = new RestClient(cardRegistration.CardRegistrationURL);

            RestRequest request = new RestRequest(Method.POST);
            request.AddParameter("data", cardRegistration.PreregistrationData);
            request.AddParameter("accessKeyRef", cardRegistration.AccessKey);
            request.AddParameter("cardNumber", cardI.Number);
            request.AddParameter("cardExpirationDate", string.Format("{0}/{1}", cardI.ExpMonth, cardI.ExpYear.ToString().Substring(2,2)));
            request.AddParameter("cardCvx", cardI.Cvc);

            IRestResponse response = client.Execute(request);

The error is : 
{"The request has been aborted: Can not create SSL / TLS secure channel."}

**Comment by SpeedOfSpin** [comment]
Have you tried setting these values first on startup

ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
