### ISSUE TITLE
Receiving PSP technical error: 009199 When I confirm mandate in sandbox

### ISSUE THREAD

**Issue by brelding92** [Mangopay/mangopay2-net-sdk#66]
Hi, 

I create the mandate under a user with First Name of "Successful".
Mandate is in state "CREATED".
I go to confirmation page, tick the checkbox, and click "confirm".
Mandate state is updated to "FAILED". 
Result details: PSP technical error: 009199.

**Comment by zineblmariouh** [comment]
how did you resolve the problem ?
