### ISSUE TITLE
Value types should be nullable in PUTs

### ISSUE THREAD

**Issue by gareththackeray** [Mangopay/mangopay2-net-sdk#7]
In, e.g. Users.UpdateLegal, the PutDTO has no constructor.  The implication of this to the user is that you can pass only the properties you want to update.  However the value type properties are not nullable so you end up passing e.g. NotSpecified for enums which is then not recognised on the other end.  

If all the value types in PUTs were made nullable this wouldn't be an issue.

Thanks.

**Comment by hobailey** [comment]
Hi @gareththackeray, thanks for flagging this up. We originally opted for NotSpecified in these cases after much debate, but I appreciate that null would perhaps be better. We're just running some further tests and will update you shortly.

**Comment by hobailey** [comment]
Hey again @gareththackeray, just to conclude that this has now been updated  with https://github.com/Mangopay/mangopay2-net-sdk/pull/8 :-)

**Comment by gareththackeray** [comment]
Thanks @hobailey - will you update nuget?

**Comment by hobailey** [comment]
@gareththackeray yes, just done that - sorry for the delay :-)
