### ISSUE TITLE
[Question], I do not understand, how to know if the user has to pay or not? (PayInCardWebPostDTO)

### ISSUE THREAD

**Issue by KhanLian** [Mangopay/mangopay2-net-sdk#72]
Hello,
I do not understand, how to know if the user has to pay or not?

Your method is not asynchronous, how do you do?

In your unit tests you do not test this method "PayinCardWebPostDTO"
My code : 
  PayInCardWebPostDTO payInCardWebPostDTO = new PayInCardWebPostDTO (authorId, new MangoPay.SDK.Entities.Money {Amount = AmountAdapter, Currency = CurrencyIso.EUR},
                   new MangoPay.SDK.Entities.Money {Amount = 0, Currency = CurrencyIso.EUR},
                   walletId, "https://www.example.com", CultureCode.FR, CardType.CB_VISA_MASTERCARD, "API");
             payInCardWebPostDTO.SecureMode = SecureMode.FORCE;
          
             PayInCardWebDTO payInCardWebDTO = api.PayIns.CreateCardWeb (key, payInCardWebPostDTO);
 return new  RedirectResult(payInCardWebDTO.RedirectURL);

(I'm beginner)

Best Regards,
Khan.

**Comment by Riwak** [comment]
Hello @KhanLian, 

You can setup easily some hook notifications directly on the `PAYIN_NORMAL_SUCCEEDED` event to know if yes or not the Payin is succeeded or failed.

Please find more info here : https://docs.mangopay.com/endpoints/v2.01/hooks#e246_the-hook-object

Best regards,

Audouin,

**Comment by KhanLian** [comment]
Hello Audouin,

It returns a transactionId, how to do?
When event failed payment or succeeded

Best Regards,

 Khan.

**Comment by Riwak** [comment]
You don't need to have a transactionId.

If you want to create a notification for the event type "PAYIN_NORMAL_SUCCEEDED" on your URL: "http://www.mynotificationurl.com" you will recieve this ping: http://www.mynotificationurl.com?EventType= PAYIN_NORMAL_SUCCEEDED&RessourceId=1309853&Date=1397037093

Where the RessourceId is the Id of the PAYIN in question.

**Comment by KhanLian** [comment]
Hello,

You don't understand my question...

I have a method for payment and i search for know a status payment.

This line >  return new RedirectResult(payInCardWebDTO.RedirectURL);

Now > when user cancel payment or success payment, user returned with url specify in the object for this : payInCardWebPostDTO and in URL i have "transactionId".

And with TransactionId i do not know if payment is a success or cancel.

Is not possible search a transactionId  for know status payment with your sdk 
How to do?

Best Regards,

Khan

**Comment by Riwak** [comment]
If you want to know if a payment is failed or not : 

- You can view a payIn status simply by doing a get on : https://docs.mangopay.com/endpoints/v2.01/payins#e265_view-a-payin with his transaction Id. You will have all the details and status of this transaction. 

- You can also setup a notification on PAYIN SUCCESS / PAYIN FAILED event. When the notification is triggered it will provide you the Id of the transaction.
